/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * Coordinates site-driven client certificate enrollment requests discovered on
 * HTTPS responses.
 */
[scriptable, uuid(8df03baa-2f95-4a97-af2b-3f77c764f8d1)]
interface nsISiteClientCertEnrollmentService : nsISupports
{
  /**
   * Handles a site's request to enroll a new client certificate.
   *
   * @param requestingURI The HTTPS URI that requested enrollment.
   * @param enrollmentURI The HTTPS endpoint that should receive a CSR.
   * @param browserId The browser id for the top-level browsing context, or 0 if
   *                  no browsing context is available.
   */
  void requestEnrollment(in AUTF8String requestingURI,
                         in AUTF8String enrollmentURI,
                         in uint64_t browserId);
};

%{C++
#define NS_SITE_CLIENT_CERT_ENROLLMENT_SERVICE_CONTRACTID \
  "@mozilla.org/security/site-client-cert-enrollment-service;1"
%}
